name: ncspot
base: core18
adopt-info: ncspot
summary: Cross-platform ncurses Spotify client written in Rust
description: |
  ncurses Spotify client written in Rust using librespot. It is heavily 
  inspired by ncurses MPD clients, such as ncmpc. My motivation was to 
  provide a simple and resource friendly alternative to the official 
  client as well as to support platforms that currently don't have a 
  Spotify client, such as the *BSDs.

grade: stable
confinement: strict

apps:
  ncspot:
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      LC_ALL: "C.UTF-8"
    command: ncspot -b "$SNAP_USER_COMMON"
    plugs:
      - network
      - network-bind
      - unity7
      - pulseaudio
    slots:
      - mpris

parts:
  ncspot:
    plugin: rust
    source: https://github.com/hrkfdn/ncspot.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l --sort=version:refname | tail -n 1 | tr -d 'v')"
      echo $last_committed_tag
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      echo $last_released_tag
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "v${last_committed_tag}"
        echo "Setting version to $last_committed_tag"
        snapcraftctl set-version "$(echo $last_committed_tag)"
      else
        echo "Setting version to $(git rev-parse --short HEAD)"
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    build-packages:
      - libasound2-dev
      - libncurses-dev
      - libncursesw5-dev
      - libssl-dev
      - libdbus-1-dev
      - pkg-config
      - libpulse-dev
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - musl-tools
    stage-packages:
      - libpulse0
      - libncursesw5
      - libasound2
      - libdbus-1-3
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libssl1.1
      - libsystemd0
      - libtinfo5
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
