name: ncspot
base: core22
version: 1.1.2
summary: Cross-platform ncurses Spotify client written in Rust
description: |
  ncurses Spotify client written in Rust using librespot. It is heavily 
  inspired by ncurses MPD clients, such as ncmpc. My motivation was to 
  provide a simple and resource friendly alternative to the official 
  client as well as to support platforms that currently don't have a 
  Spotify client, such as the *BSDs.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  ncspot:
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/"
      LC_ALL: "C.UTF-8"
      ALWAYS_USE_PULSEAUDIO: '1'
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    command-chain: ["snap/command-chain/alsa-launch"]
    command: bin/launcher
    plugs:
      - alsa
      - network
      - network-bind
      - unity7
      - audio-playback
      - removable-media
    slots:
      - mpris

parts:
  launcher:
    plugin: dump
    source: snap/local
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  ncspot:
    after: [alsa-mixin]
    plugin: rust
    source: https://github.com/hrkfdn/ncspot/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    source-tag: 
    build-packages:
      - cargo
      - libasound2-dev
      - libncurses-dev
      - libncursesw5-dev
      - libssl-dev
      - libdbus-1-dev
      - pkg-config
      - libpulse-dev
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - musl-tools
    stage-packages:
      - libpulse0
      - libncursesw5
      - libasound2
      - libdbus-1-3
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libssl3
      - libsystemd0
      - libtinfo5
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
